# -*- coding: utf-8 -*-
"""
IE3: preferred IDs (sin acentos / truncados) -> Nickname exacto del CSV.
Formato: preferred_id<TAB>juego_nick
"""

import json
from pathlib import Path

DATA_RAW = Path(__file__).resolve().parent.parent / "data" / "raw"
DATA_RAW.mkdir(parents=True, exist_ok=True)

# (preferred_id, juego3 Nickname exacto)
PAIRS = [
    ("Mark", "Mark"),
    ("Darren", "LaChance"),
    ("Jack", "Jack"),
    ("Banyan", "Banyan"),
    ("Archer", "Hawkins"),
    ("Tod", "Tod"),
    ("Nathan", "Nathan"),
    ("Hurley", "Kane"),
    ("Thor", "St’berg"),
    ("Jordan", "Jordan"),
    ("Caleb", "Stonew’l"),
    ("Jude", "Jude"),
    ("Samford", "Samford"),
    ("Shawn", "Froste"),
    ("Xavier", "Xavier"),
    ("Kevin", "Kevin"),
    ("Austin", "Hobbes"),
    ("Axel", "Axel"),
    ("Whale", "Whale"),
    ("C-Horse", "C-Horse"),
    ("Barracuda", "Barracu."),
    ("Beaches", "Beaches"),
    ("Water", "Water"),
    ("Turtle", "Turtle"),
    ("Kraken", "Kraken"),
    ("Dolphin", "Dolphin"),
    ("Prawn", "Prawn"),
    ("K-Rab", "K-Rab"),
    ("Hang-Ten", "Hang-Ten"),
    ("Fisher", "Fisher"),
    ("Summers", "Summers"),
    ("Reef", "Reef"),
    ("Jaws", "Jaws"),
    ("Marlin", "Marlin"),
    ("Mustafa", "Mustafa"),
    ("Hamad", "Hamad"),
    ("Kalil", "Kalil"),
    ("Wali", "Wali"),
    ("Farooq", "Farooq"),
    ("Sylla", "Sylla"),
    ("Ahmed", "Ahmed"),
    ("Jibril", "Jibril"),
    ("Armand", "Armand"),
    ("Sulaiman", "Sulaiman"),
    ("Jasim", "Jasim"),
    ("Massoud", "Massoud"),
    ("Rajab", "Rajab"),
    ("Abdulla", "Abdulla"),
    ("Siddique", "Siddique"),
    ("Majdi", "Majdi"),
    ("Jung-Soo", "Jeongsu"),
    ("Ho", "Ho"),
    ("Hwang", "Hwang"),
    ("Hong", "Hong"),
    ("Minho", "Minho"),
    ("Ko", "Ko"),
    ("Seul", "Seul"),
    ("Choi", "Choi"),
    ("Park", "Park"),
    ("Kim", "Kim"),
    ("Yi", "Yi"),
    ("Ja", "Ja"),
    ("Aphrodite", "Aphrodi."),
    ("Torch", "Torch"),
    ("Gazelle", "Gazelle"),
    ("Noh", "Noh"),
    ("McQueen", "McQueen"),
    ("Jeeves", "Jeeves"),
    ("Gazzer", "Gazzer"),
    ("Buckingham", "Bucking."),
    ("Lance", "Rawton"),
    ("Ripper", "Ripper"),
    ("Squall", "Squall"),
    ("Cole", "Cole"),
    ("Mane", "Mane"),
    ("Appleton", "Appleton"),
    ("Eric", "Purplet."),
    ("Pounding", "Pounding"),
    ("Richards", "Richards"),
    ("Partinus", "Partinus"),
    ("Owen", "Owen"),
    ("Woodgate", "Woodgate"),
    ("Ortega", "Ortega"),
    ("Cruz", "Cruz"),
    ("Therese", "Thiago"),
    ("Acosta", "Acosta"),
    ("Diaz", "Dｾaz"),
    ("Martinez", "Martｾnez"),
    ("Tevez", "Tｺvez"),
    ("Carlos", "Carlos"),
    ("Sergio", "Pｺrez"),
    ("Roberto", "Roberto"),
    ("Castillo", "Castillo"),
    ("Samuel", "Samuel"),
    ("Leone", "Badigo"),
    ("Oro", "Oro"),
    ("Saviola", "Saviola"),
    ("Aguero", "Agﾌero"),
    ("Dash", "Dash"),
    ("Hawke", "Hawke"),
    ("Bryant", "Bryant"),
    ("Strider", "Strider"),
    ("Dynamo", "Dynamo"),
    ("Bobby", "Bobby"),
    ("Rob", "Washing."),
    ("Bob", "The Slob"),
    ("Woodmark", "Woodmark"),
    ("Erik", "Erik"),
    ("Pierce", "Pierce"),
    ("Krueger", "Krueger"),
    ("Pooma", "Pooma"),
    ("Keats", "Keats"),
    ("Jax", "Jax"),
    ("Dexter", "Dexter"),
    ("Blasi", "Blasi"),
    ("Sanctis", "Sanctis"),
    ("Galliano", "Galliano"),
    ("Nobili", "Nobili"),
    ("Graziuso", "Graziuso"),
    ("Maserati", "Maserati"),
    ("Carnivale", "Cannav."),
    ("Gabrini", "Gabrini"),
    ("Giorgio", "Giorgio"),
    ("Diavolo", "Diavolo"),
    ("Zanardi", "Zanardi"),
    ("Enrico", "Oliviero"),
    ("Rossa", "Rossa"),
    ("Nakata", "Nakata"),
    ("Bianchi", "Bianchi"),
    ("Generani", "Generani"),
    ("Falcao", "da Silva"),
    ("Ribeiro", "Ribeiro"),
    ("Lagarto", "Lagarto"),
    ("Bagre", "Bagre"),
    ("Monstro", "Monstro"),
    ("Clemens", "Clemens"),
    ("Nogueira", "Nogueira"),
    ("Oliveira", "Oliveira"),
    ("Passos", "Passos"),
    ("Barboza", "Barboza"),
    ("Cerezo", "Cerezo"),
    ("Almeida", "Almeida"),
    ("Mendes", "Mendes"),
    ("Robingo", "Robingo"),
    ("Gato", "Gato"),
    ("Santos", "Santos"),
    ("Helio", "Helio"),
    ("Keenan", "Keenan"),
    ("Vitesse", "Vitesse"),
    ("Mountain", "Mountain"),
    ("Gaines", "Gaines"),
    ("Ferrum", "Ferrum"),
    ("Mangrove", "Mangrove"),
    ("Hampton", "Hampton"),
    ("Haddad", "Haddad"),
    ("Ryan", "Ryan"),
    ("Maximino", "Maximino"),
    ("Vitrum", "Vitrum"),
    ("Leung", "Leung"),
    ("Hedgeer", "Hedgeer"),
    ("Flare", "Flare"),
    ("Drago", "Drago"),
    ("Lazuli", "Lazuli"),
    ("Quarzo", "Quarzo"),
    ("Diamante", "Diamante"),
    ("Turchese", "Turchese"),
    ("Agata", "Agata"),
    ("Zaffiro", "Zaffiro"),
    ("Berillo", "Berillo"),
    ("Smeraldo", "Smeraldo"),
    ("Granato", "Granato"),
    ("Topazio", "Topazio"),
    ("Corniola", "Corniola"),
    ("Rubino", "Rubino"),
    ("Acuto", "Acuto"),
    ("Ametista", "Ametista"),
    ("Perla", "Perla"),
    ("Opale", "Opale"),
    ("Civet", "Civet"),
    ("Bear", "Bear"),
    ("Jackal", "Jackal"),
    ("Minion", "Minion"),
    ("Buffalo", "Buffalo"),
    ("Dingo", "Dingo"),
    ("Spider", "Spider"),
    ("Bfly", "B’fly"),
    ("Owl", "Owl"),
    ("Hedgehog", "Hedgehog"),
    ("Mantis", "Mantis"),
    ("Crow", "Crow"),
    ("Zebra", "Zebra"),
    ("Coyote", "Coyote"),
    ("Scorpio", "Scorpio"),
    ("Gator", "Gator"),
    ("Sanchez", "Sｲnchez"),
    ("Espindola", "Espind."),
    ("Naval", "Naval"),
    ("Costa", "Costa"),
    ("Lopez", "Lﾄpez"),
    ("Gallego", "Gallego"),
    ("Castor", "Castor"),
    ("Nadal", "Nadal"),
    ("Ferreira", "Ferreira"),
    ("Pereira", "Pereira"),
    ("Moreno", "Moreno"),
    ("Arroyo", "Arroyo"),
    ("Mayo", "Mayo"),
    ("Peroque", "Peroquｺ"),
    ("Cesar", "Cｺsar"),
    ("Rubiera", "Rubiera"),
    ("Pialat", "Pialat"),
    ("Lazare", "Lazare"),
    ("Godin", "Godin"),
    ("Aron", "Aron"),
    ("Poujol", "Poujol"),
    ("Pinot", "Pinot"),
    ("Pinson", "Pinson"),
    ("Gutain", "Gutain"),
    ("Porec", "Pｺrec"),
    ("Huysmans", "Huysmans"),
    ("Hinault", "Hinault"),
    ("Rousseau", "Rousseau"),
    ("Moreau", "Moreau"),
    ("Hervaud", "Hervaud"),
    ("Favreau", "Favreau"),
    ("Morland", "Morland"),
    ("Baloi", "Baloi"),
    ("Makebe", "Makebe"),
    ("Furman", "Furman"),
    ("Fana", "Fana"),
    ("Molelo", "Molelo"),
    ("Tobler", "Tobler"),
    ("Booysen", "Booysen"),
    ("McCarthy", "McCarthy"),
    ("Marunga", "Marunga"),
    ("Nortje", "Nortje"),
    ("Ines", "Ines"),
    ("Mahlangu", "Mahlangu"),
    ("Sepeng", "Sepeng"),
    ("Tswane", "Tswane"),
    ("Zamani", "Zamani"),
    ("De-Villiers", "De Vill."),
    ("Anorel", "Anorel"),
    ("Nenel", "Nenel"),
    ("Genel", "Genel"),
    ("Ekadel", "Ekadel"),
    ("Lephiel", "Lephiel"),
    ("Sachinel", "Sachinel"),
    ("Wenel", "Wenel"),
    ("Nuel", "Nuel"),
    ("Ientel", "Ientel"),
    ("Gaiel", "Gaiel"),
    ("Sanctus", "Sanctus"),
    ("Astaroth", "Astaroth"),
    ("Bael", "Bael"),
    ("Abigor", "Abigor"),
    ("Behemoth", "Behemoth"),
    ("Belial", "Belial"),
    ("Malphas", "Malphas"),
    ("Glasya", "Glasya"),
    ("Jezebeth", "Jezebeth"),
    ("Arachne", "Arachne"),
    ("Thanatos", "Thanatos"),
    ("Destra", "Destra"),
]


def main():
    nicks = [p for p, _ in PAIRS]
    aliases = {p: j for p, j in PAIRS if p != j}

    (DATA_RAW / "nicks_ie3.txt").write_text("\n".join(nicks) + "\n", encoding="utf-8")
    (DATA_RAW / "nicks_ie3_aliases.json").write_text(
        json.dumps(aliases, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote nicks_ie3.txt ({len(nicks)})")
    print(f"Wrote nicks_ie3_aliases.json ({len(aliases)} aliases)")


if __name__ == "__main__":
    main()
